# Generated by Django 3.0 on 2021-02-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reportInfo',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('reportName', models.CharField(max_length=255)),
                ('created', models.DateTimeField(max_length=20)),
                ('updated', models.DateTimeField(max_length=20)),
                ('isdel', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'reportInfo',
            },
        ),
    ]
