# Generated by Django 3.0 on 2021-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfulApiTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='period',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='created',
            field=models.DateTimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='updated',
            field=models.DateTimeField(max_length=255),
        ),
    ]
