# Generated by Django 3.0 on 2021-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfulApiTest', '0002_auto_20210202_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='reportName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
